{{- $kubeconfig_path := printf "secrets/%s" $.Values.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fakefish-kubevirt-kubeconfig
  namespace: {{ $.Values.vm_namespace }}
  labels:
    demo: ztp-cnv
type: Opaque
data:
  {{ (.Files.Glob $kubeconfig_path).AsSecrets | indent 2 }}